#!/usr/bin/env bash

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

bin=$(dirname -- "${BASH_SOURCE-$0}")
bin=$(cd -- "$bin"; pwd)

TRAINDB_JDBC_PREFIX=$(cd -- "$bin/.."; pwd -P)
lib=$TRAINDB_JDBC_PREFIX/lib

if [ -z "$JAVA_HOME" ]; then
    echo "Error: JAVA_HOME is not set" >&2
    exit 1
fi

JAVA=$JAVA_HOME/bin/java
JAVA_HEAP_MAX=-Xmx16G

if [ -n "$TRAINDB_JDBC_HEAPSIZE" ]; then
    JAVA_HEAP_MAX=-Xmx${TRAINDB_JDBC_HEAPSIZE}m
fi

TRAINDB_OPTS="$JAVA_HEAP_MAX"

# uncomment if you want to attach a debugger
#TRAINDB_OPTS="$TRAINDB_OPTS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

CLASSPATH=$lib/*:$CLASSPATH

exec "$JAVA" -cp $CLASSPATH $TRAINDB_OPTS traindb.cli.Tisql "$@"
